ALTER TABLE users ADD COLUMN IF NOT EXISTS username VARCHAR(100);
ALTER TABLE users ALTER COLUMN nome_completo DROP NOT NULL;
ALTER TABLE users ALTER COLUMN telefone DROP NOT NULL;
ALTER TABLE users ALTER COLUMN email DROP NOT NULL;
ALTER TABLE users ALTER COLUMN data_nascimento DROP NOT NULL;
ALTER TABLE users ALTER COLUMN cidade_estado DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_idx
    ON users (LOWER(username))
    WHERE username IS NOT NULL;
