ALTER TABLE poker_tables
    ADD COLUMN IF NOT EXISTS occupied_seats JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS password TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(255) NOT NULL DEFAULT 'Clube',
    ADD COLUMN IF NOT EXISTS creator_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS current_pot BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS community_cards JSONB,
    ADD COLUMN IF NOT EXISTS current_dealer INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS current_turn INT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS poker_table_states (
    table_id UUID PRIMARY KEY REFERENCES poker_tables(id) ON DELETE CASCADE,
    state JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS poker_tables_updated_at_idx ON poker_tables(updated_at DESC);
